name: tests

on:
  push:
    branches:
    - main
 
jobs:
  run-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start Test containers
      run: docker-compose -f "docker-compose.yml" up --exit-code-from form3-client-api form3-client-api

    - name: Stop Test containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
